# Generated by Django 2.1.8 on 2019-10-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('price', models.FloatField()),
                ('number', models.IntegerField()),
                ('production', models.DateTimeField()),
                ('safe_date', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='Qshop/img/a.jpg', upload_to='Qshop/img')),
                ('description', models.TextField()),
            ],
        ),
    ]
