# Generated by Django 2.1.8 on 2019-10-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='statue',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
