# Generated by Django 2.1.8 on 2019-10-30 17:17

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Qshop', '0002_goods_statue'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('picture', models.ImageField(default='/qshop/img/1.jpg', upload_to='SHOP/static/img')),
            ],
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='goods',
            name='statue',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Qshop.GoodsType'),
            preserve_default=False,
        ),
    ]
