# Generated by Django 2.1.8 on 2019-10-31 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qshop', '0003_auto_20191030_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='identity',
            field=models.IntegerField(default=0),
        ),
    ]
