# Generated by Django 2.1.8 on 2019-10-31 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Quser', '0002_quser_identity'),
        ('Qshop', '0004_goods_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='identity',
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Quser.Quser'),
            preserve_default=False,
        ),
    ]
