# Generated by Django 2.1.8 on 2019-11-05 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Buyer', '0002_auto_20191104_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='buycat',
            name='goods_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
